Scrum 18 actualizar formulario  ubicaciones y forms relacionados
Tech-Work-Solutions/Minuta-Seguridad-JBS pull request #8
Opened 2024-12-17 04:52 UTC by oscardariopb

En este PR se agrega las siguientes funcionalidades:

1. Sede_id a minutas, visitantes y vehiculos.
2. Agregar sede_id a la configuración en la vista de ubicaciones.

2024-12-17 15:04 UTC, oskr93 requested changes

2024-12-17 15:04 UTC, oskr93 commented on resources/js/pages/admin/dashboard/settings/tabs/Ubicacion.vue
> +      await axios.post('/api/registerUbicacion', this.formData).then((response) => {
Si está usando async en la funcion principal, No creo sea necesario el then

2024-12-18 03:21 UTC, oscardariopb commented on resources/js/pages/admin/dashboard/records/Minuta.vue
> +         axios.get(url).then((response) => {
En este caso eliminé el await que ya existía no cambie la funcionalidad, además, el await no tenía sentido dejarlo. Pero ya hago su sugerencia.

2024-12-18 03:56 UTC, oscardariopb commented on resources/js/pages/admin/dashboard/settings/tabs/Ubicacion.vue
> +      await axios.post('/api/registerUbicacion', this.formData).then((response) => {
solo indente xD

2024-12-19 04:33 UTC, carlosstevenh approved these changes
LGTM

2024-12-19 04:36 UTC, merged